/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Oliver
 */
public class SearchMaterial extends javax.swing.JPanel {

    private int material;

    /**
     * Creates new form SearchMaterial
     */
    public SearchMaterial(int materialOption) {
        this.material = materialOption;
        initComponents();
        // Delete this when you start working
        switch (this.material) {
            case 1:
                lblMaterial.setText("Material seleccionado: Libro");
                break;
            case 2:
                lblMaterial.setText("Material seleccionado: Revista");
                break;
            case 3:
                lblMaterial.setText("Material seleccionado: CD");
                break;
            case 4:
                lblMaterial.setText("Material seleccionado: DVD");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 240));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));

        jLabel1.setText("Buscar material");

        lblMaterial.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(lblMaterial)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addGap(128, 128, 128)
                .addComponent(lblMaterial)
                .addContainerGap(454, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMaterial;
    // End of variables declaration//GEN-END:variables
}
